name: Makefile CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache mops packages
        uses: actions/cache@v3
        with:
          key: mops-packages-${{ hashFiles('mops.toml') }}
          path: |
            ~/.cache/mops
            ~/mops

      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.15.1

      - name: Install mops & mocv
        run: |
            npm -g i mocv
            npm --yes -g i ic-mops@0.34.0
            mops i

      # mops test uses this path internally
      - name: Set DFX MOC Path
        run: | 
          make set-moc-version
          echo "DFX_MOC_PATH=$(mocv bin)/moc" >> $GITHUB_ENV

      - name: install wasmtime
        run: |
          bash -ci "$(curl -fsSL https://wasmtime.dev/install.sh)" -- --version v13.0.0
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      # - name: Detect warnings
      #   run: make check

      - name: Run Tests
        run: mops test