name: Makefile CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          vessel-version: 0.6.3
          dfx-version: 0.13.1

      - name: install mops
        run: |
            npm --yes -g i ic-mops
            mops i

      - name: install wasmtime
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      - name: Detect warnings
        run: make no-warn

      - name: Run Tests
        run: make compile-tests