name: Makefile CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache mops packages
        uses: actions/cache@v3
        with:
          key: mops-packages-${{ hashFiles('mops.toml') }}
          path: |
            ~/.cache/mops
            ~/mops

      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.15.0

      - name: Install mops & mocv
        run: |
            npm -g i mocv
            npm --yes -g i ic-mops
            mops i

      - name: install wasmtime
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      - name: Detect warnings
        run: make check

      - name: Run Tests
        run: make test